spring.application.name=Wave
spring.datasource.url=jdbc:postgresql://localhost:5432/wavedb
spring.datasource.username=waveuser
spring.datasource.password=wavepass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.docker.compose.enabled=false
spotify.client-id=${SPOTIFY_CLIENT_ID}
spotify.client-secret=${SPOTIFY_CLIENT_SECRET}
message.encryption-key=${MESSAGE_ENCRYPTION_KEY}
spring.cache.type=simple
spring.security.user.name=user
spring.security.user.password=123456